### ISSUE TITLE
[Renegade] Verificar cuál Carrito Compras es Válido

### ISSUE THREAD

**Issue by esauml** [rubenramosDev/renegade#25]
Verificar con equipo qué status(INT) es el válido para carrito compras en BD. Status: 1 ?

**Comment by esauml** [comment]
@RichardJohnRx @coverend94 help plis

**Comment by rubenramosDev** [comment]
El carrito de compras tiene una propiedad llamada Activo.
Entonces, mientras esta propiedad sea True, este el carrito Valido. Cuando el cliente hace la compra de los productos, este carrito queda Inactivo (Activo = False) y se crea uno nuevo con el atributo Activo = True.
@esauml

**Comment by rubenramosDev** [comment]
PD. Por ende, el usuario solo puede tener un Carrito activo  (Activo = True) a la vez.
