### ISSUE TITLE
[Renegade] Run-Time toma mucho tiempo en carrito

### ISSUE THREAD

**Issue by esauml** [rubenramosDev/renegade#37]
Para consultar el listado de producto que se tiene en el carrito, toma mucho en ejecutarse la petición.

Posible solución: Mejorar los scripts en Queries

**Comment by rubenramosDev** [comment]
Por qué? Solo tenemos 10 productos, lol

**Comment by esauml** [comment]
No sé, ayer me dos veces tardo varios segundos pero en ese momento se me habían acabado los datos, pero aún así los datos no deberían de influir en eso.

**Comment by rubenramosDev** [comment]
No creo que sea tema de BD. Considero que viene de estilos y referencias a CDN en el layout. Quizás tu internet estaba lento. ¿Haz hecho otroas pruebas en tu casa?

**Comment by esauml** [comment]
Ya no he hecho, pruebas en esto por el momento. Cuando tenga las pruenas, hago un update por aquí
