### ISSUE TITLE
Consideras que no se puede vender más del stock disponible por Producto? Al cliente

### ISSUE THREAD

**Issue by rubenramosDev** [rubenramosDev/renegade#44]
@esauml @tujeta03gg

**Comment by esauml** [comment]
Hola. Pienso que así debería ser. Antes había un tabla pedido para esos casos pero con lo que nos dijo el profe de BD lo quitamo y ahora está lo de stock minimo #15 

Pero podría ser un área de mejora, que un cliente pueda pedir productos que estuvieran fuera de stock. 

Por ahora no hacerlo, pero tal vez agregar una apartado en la presentación de areas de mejora/oportunidad. ¿Qué piensas?

**Comment by rubenramosDev** [comment]
Es más simple lo que cometo.... Solo quería saber si estabas tomando en cuenta la propiedad de *stock* que se agregó en la tabla de Producto cuando enlistas las cantidades disponibles.

**Comment by esauml** [comment]
Entonces sí 😅 solo se puede vender del stock disponible. 

Cuando se entra al detalle de producto aparece el stock dispoble y un input que tiene como máximo la cantidad de stock
