### ISSUE TITLE
Materia prima - Costo

### ISSUE THREAD

**Issue by rubenramosDev** [rubenramosDev/renegade#47]
Tenemos un tema importante en cuestión de diseño de BD. No podemos comprar materia prima difectamente, ya que desconocemos el costo de la misma. ¿Propuestas?

Toma relevancia este problema porque seguramente durante la presentación nos pidan hacer un flujo completo de negocio.

**Comment by esauml** [comment]
Buen punto. 🤔 

Por ahora se puede tomar el precio de la última orden de compra, así nos safamos de este pedo.

Pero creo que lo correcto es hacer lo mismo que con el sock de productos, tener mínimo y máxima de MateriaPrima y que le llegue una notificación el administrativo que hay poca materia prima y que se debe reabastecer. Esto ya de por medio, no ir automatizado, osea que se ejecute una orden de compra cuando no hay materia prima

**Comment by rubenramosDev** [comment]
@coverend94 working on it.
