### ISSUE TITLE
Tabla producto sin precio?

### ISSUE THREAD

**Issue by rubenramosDev** [rubenramosDev/renegade#7]
CREATE TABLE IF NOT EXISTS Producto
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    nombre      VARCHAR(50) NOT NULL,
    descripcion TEXT        NOT NULL
);

@RichardJohnRx Es correcto esto?

**Comment by RichardJohnRx** [comment]
No, ya se está corrigiendo

**Comment by rubenramosDev** [comment]
@esauml tienes excepcion en la clase Producto por el precio.

**Comment by rubenramosDev** [comment]
> No, ya se está corrigiendo

Aprovcha para agregar el campo de image_url

**Comment by esauml** [comment]
> @esauml tienes excepcion en la clase Producto por el precio.

Esto lo tiene que corregir la persona que se encargue de cambiar el módulo a la nueva BD. Vean el issue #8
